application: proyectoals
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: handlers.main.app

- url: /reviews/nueva
  script: handlers.reviews.nueva.app
  login: required

- url: /reviews/elimina
  script: handlers.reviews.elimina.app
  login: required

- url: /reviews/mis_reviews
  script: handlers.reviews.mis_reviews.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "latest"
